language: python
python: 3.6
cache:
  pip: true
  directories:
    - "$TRAVIS_BUILD_DIR/.tox"

stages:
  - linting
  - test

install:
  - pip install tox-travis poetry==1.0.0b3

script:
  - tox

jobs:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
      dist: xenial
      before_script:
        - pip install coveralls
      after_success:
        - coveralls

    - stage: linting
      python: 3.7
      dist: xenial
      install:
        - pip install -U pre-commit
      script:
        - pre-commit run --all-files --verbose
      env:
        - PRE_COMMIT_HOME="$TRAVIS_HOME/.cache/pre-commit"
      cache:
        pip: true
        directories:
          - "$PRE_COMMIT_HOME"
