language: python
python: 3.6
cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

stages:
  - linting
  - test

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python - -y --preview
  - source $HOME/.poetry/env
  - poetry install --verbose --no-interaction

script:
  - pytest

jobs:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
      dist: xenial
      before_script:
        - pip install coveralls
      after_success:
        - coveralls

    - stage: linting
      python: 3.7
      dist: xenial
      install:
        - pip install -U pre-commit
      script:
        - pre-commit run --all-files --verbose
      env:
        - PRE_COMMIT_HOME="$HOME/.cache/pre-commit"
      cache:
        pip: true
        directories:
          - "$PRE_COMMIT_HOME"
